#!/bin/bash
base="$PWD"
echo "#######################################"
echo $base
echo "#######################################"

echo "Pull git repos"

echo "#######################################"
echo "#######################################"
echo "#######################################"
echo "Pull rover-main"
pushd "$base/rover-main"
git pull
git checkout "947c9c2e975736b3a55c829f41832064a9edd1b5"
git submodule update --recursive

echo "Pull suqc"
pushd "$base/suq-controller"
git pull
git checkout "b1c87aaf5fff99927e050f1595978ead5b3a1db9"

echo "#######################################"
echo "#######################################"
echo "#######################################"
