#!/bin/bash
base="$PWD"
echo "#######################################"
echo $base
echo "#######################################"

echo "Pull git repos"

echo "#######################################"
echo "#######################################"
echo "#######################################"
echo "Pull rover-main"
pushd "$base/rover-main"
git pull
git checkout "24df459da93147117ea8e5402176deb7d93ce5fd"
git submodule update --recursive

echo "Pull suqc"
pushd "$base/suq-controller"
git pull
git checkout "b1c87aaf5fff99927e050f1595978ead5b3a1db9"

echo "#######################################"
echo "#######################################"
echo "#######################################"
