#!/bin/bash

echo "Pull git repos"

echo "#######################################"
echo "#######################################"
echo "#######################################"
echo "Pull rover-main"
pushd "$PWD/rover-main"
git pull
git checkout "24df459da93147117ea8e5402176deb7d93ce5fd"
git submodule update --recursive

echo "Pull suqc"
pushd "$PWD/suq-controller"
git pull
git checkout "91b1e91140a2dbd29fe7d9eae9a02719e61f3b88"

echo "#######################################"
echo "#######################################"
echo "#######################################"
